### ISSUE TITLE
How to handle HTTP Basic Authentication?

### ISSUE THREAD

**Issue by PavelOnz** [FluentLenium/FluentLenium#1066]
Dear amazing FluentLenium team, i'm just switching from plain Selenium to your wonderful framework. I was wondering, what is the recommended way of dealing with HTTP basic authentication. How can i supply the credentials into the base URL in a proper way? 

I dont see a way, how to enter the credentials using Alert, and i'm unable to add the credentials into the baseURL. Thanks!

BR,
Pavel

**Comment by picimako** [comment]
Hi @PavelOnz!

Thank you for the kind words. :)

If you configure the base URL in a format like `https://<username>:<pwd>@my.domain.com/`, e.g. `https://admin:123@my.domain.com/` that should get your through the basic authentication. At least that is how it worked for me last time I needed such thing.

**Comment by PavelOnz** [comment]
Hi @picimako , getting back to this after a long time. I assumed you meant to overload the "getBaseUrl()" method, which i already tried. Also tried to overload "getUrl()", or putting the credentials to @PageUrl annotation. All attempts ends up the same - showing chrome with alert/prompt to enter basic auth creds. As i understand, selenium is not able to add request headers. Using WebDriverWait and Alert does not work either (same result), and i would like to completely avoid any hard-set timeouts. Any other ideas by chance? Thanks!

**Comment by picimako** [comment]
@PavelOnz 
I've just double-checked how my last project was set up, and there I had `FluentCucumberTest` extended to make a base test class, and I overridden the `getBaseUrl()` method.
When we had the basic authentication alert we used FluentLenium version 4.2.2 and 4.3.0.

Selenium itself cannot alter request headers, for that you'll need a library such as browsermob-proxy.

My guess is that whatever way you would open the URL, if the basic auth credentials are provided in the URL, int the format I mentioned, it should bypass the alert. But it seems like it's not the case in your case.

I can also imagine that the application you are testing might ignore those crendetials and may try to enforce the authentication.

If supplying the credentials via URL won't work, an alternate solution might be to handle the alert via `FluentJavascript.executeScript()` (or `JavascriptExecutor` in plain Selenium) and supplying the credential values from system properties or environment variables, so that you won't have them hardcoded.

**Comment by PavelOnz** [comment]
Hmm, it seems there are several issues combined - first, the website seems to first send HTTP 301 (perm redir), and the redir target is the one sending the Auth challenge. 
I cannot even use the URL-embedded credentials in chrome "manually" - always getting the creds prompt. Firefox gets confused as well, and notifies, that user is sending credentials to a page, which does not require it.  
Moreover, firefox, after submitting the URL with embedded creds displays an alert about passing creds this way => needs to be handled by alert() functions.

Now the more strange stuff - The first version of UI tests launcher i wrote without Fluentlenium, using only raw Selenium works fine, and the credentials are accepted. In this case, im just doing a really dumb string concat, and the test works.

In all cases, i'm using locally installed Chrome in version 84 with corresponding ChromeDriver, and Firefox 79. 

` if (isAuthEnabled) {
            LOG.debug("HTTP Basic is enabled.");
            try {
                URL url = new URL(targetURL + urlPathPrefix);
                this.siteFinalURL = url.getProtocol() +
                        "://" +
                        authUser +
                        ":" +
                        authPassword +
                        "@" +
                        url.getHost() +
                        url.getFile() +
                        pageUrlPath;
            } catch (MalformedURLException e) {
                LOG.error("Site root URL is malformed, please check the \"uitest-client.properties\", option \"testsuite.project.site.url\"");
            }
        } else {
            LOG.debug("HTTP Basic is disabled");
        }`

How does the Fluentlenium pass the URL to the Selenium? Do you somehow modify/trim the BaseURL internally?

**Comment by filipcynarski** [comment]
Not the Framework issue - implementation related challenge  sorry there is to plenty of us to write the code for you
