### ISSUE TITLE
Make FluentWaitMatcher available with a functional selector

### ISSUE THREAD

**Issue by Toilal** [FluentLenium/FluentLenium#203]
When using ```await().until("#someElement")```, it returns a FluentWaitMatcher object to perform advanced conditions like ```hasAttribute```, ```hasText```, ```hasClass```, etc ...

Same features should be available with some functional selector.

```
await().untilElement((f) -> f.findFirst("#someElement")).hasClass(...);
```

**Comment by logineimer** [comment]
`FluentWaitMatcher` uses the `selector` (e.g. `#someElement`) for several purposes. For example, `hasIdMessage(selector, value)` is called with the `selector` property.

For the first try, I implemented a method which takes the functional selector as an argument. The signature looks as follows:
`public FluentWaitMatcher untilElement(Function<Fluent, FluentWebElement> selector)`

FluentLenium is unable to retrieve the String `selector` from a `FluentWebElement` retrieved by the functional selector. My first approach to implement the feature includes distinguishing between String and functional selector in the private `FluentWaitMatcher.find()` method. However, this isn't a clean approach because `FluentWaitMatcher` uses the String selector for several purposes as stated above.

Any ideas?

**Comment by logineimer** [comment]
The second problem results from the different return types of `find()` and `findFirst()` which will return a `FluentWebElement` and a `FluentList<FluentWebElement>` respectively. The lambda expression can only handle one return type because they both don't define a common interface.

**Comment by Toilal** [comment]
For the first problem, I think the selector is only used to generate a message that will be displayed on failed wait. I don't think it's a problem if we can't retrieve the effective selector, and we could use toString() on the functional selector instead.

For the second, we could implement two distinct methods : 

```
public FluentWaitMatcher untilElement(Function<Fluent, FluentWebElement> selector)

public FluentWaitMatcher untilElements(Function<Fluent, FluentList<FluentWebElement>> selector)
```

But the more I use fluentlenium, and the more I think there's a mass refactoring to do.

For example, ```FluentList<FluentWebElement>``` and ```FluentWebElement``` should implement a common interface, and selectors could use this interface instead, in order to use the same function signature. It will then be possible to have a single ```untilElement``` function.

**Comment by logineimer** [comment]
I totally agree with your point. A common interface for those classes is necessary. I've had the same idea of two distinct methods for single and multi select. However, this would make the code less readable and maintainable.

Maybe, it's the best to postpone this issue until refactoring is done.
