### ISSUE TITLE
Add Spring support in dedicated module

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#337]
Now, it is impossible to pass configuration class through fluentlenium.properties if the class is configured by Spring.

We need to add separate FluentLenium module w/ spring support.

**Comment by filipcynarski** [comment]
We figured out that is no Spring support in all features like WebDriverFactory.

**Comment by jltnf54** [comment]
Are there any plans to fully support Spring,  meaning using @Page objects as Spring beans, and injecting services into Page objects?

**Comment by filipcynarski** [comment]
@jltnf54 it is working w/ Spring w/o any issues. But doesn't work w/ this new configuration feature. So you can use FluentLenium w/ Spring :) Please let me know if you have any further questions.

**Comment by jltnf54** [comment]
Do you have any examples?

**Comment by filipcynarski** [comment]
I think we should add it in examples section. I'll add a task in our backlog to prepare something.

**Comment by filipcynarski** [comment]
@jltnf54 example added in favor of #347 you can take a look on spring-example project in fluentlenium-examples module.

**Comment by Toilal** [comment]
Autowiring a `FluentPage` will not work, because `FluentPage` requires `FluentControl` constructor parameter. Also, Spring injection will not occur in FluentPage too, so `browserService` will be null in your case.

So we are planning a `fluentlenium-spring` module to support the following features

- Accept @Autowired instead of @Page for Page injection (=> not sure it's doable as the FluentLenium Injection may not be consistent with the Spring Injection. But in itself, it's not a big issue, and following points are more critical).
- Allow @Autowired of fields in FluentPage.
- Allow to configure FluentLenium configuration properties from Spring context, with a Spring bean implementing `org.fluentlenium.configuration.ConfigurationProperties`.
- For configuration properties currently accepting a JavaBean Class Name  (ie. webDriver, capabilities, ...), allow to give a Spring Bean name instead available in the spring context.

**Comment by Toilal** [comment]
As a workaround for the FluentPage issue you can still use @Page, and use JUnit @Before to inject manually the context into the pages.

see http://stackoverflow.com/questions/3813588/how-to-inject-dependencies-into-a-self-instantiated-object-in-spring

**Comment by slawekradzyminski** [comment]
Not sure what should be done here. FL works well with Spring, we even have example.
