### ISSUE TITLE
Spring usage w/ FluentLenium example

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#347]
We need to present how to use FluentLenium w/ Spring.

Example project should be added to help users to start with it.

**Comment by jltnf54** [comment]
thanks.  I was wondering if this is an okay approach to integrating with spring.

@RunWith(SpringJUnit4ClassRunner.class)
@SpringBootTest(classes = Application.class)
public abstract class AbstractFluentTest extends FluentTest {

	@Autowired
	WebDriver webDriver;

	@Autowired
	MyProperties quotesProperties;

	@Override
	public WebDriver newWebDriver() {
		return webDriver;
	}

	@Override
	public String getBaseUrl() {
		return myProperties.getBaseUrl();
	}
}

@ActiveProfiles("dev-chrome")
public class InitialTest extends AbstractFluentTest {

	@Autowired
	LoginPage loginPage;

	@Before
	public void beforeTest() {
		inject(loginPage);
	}

	@Test
	public void testPages()  {
		loginPage.go();
		assertThat(loginPage).isAt();
		loginPage.login("xxxx", "xxx");
	}

}

@Component
public class LoginPage extends FluentPage {

	@Autowired
	private static BrowserService browserService;

	@Override
	public String getUrl() {
		return "/";
	}

	public void login(String username, String password) {
		$("#username").fill().with(username);
		$("#password").fill().with(password);
		$(".btn-primary").click();
	}

}

@Service
public class BrowserService {
....
}

@SpringBootApplication(scanBasePackages = "my.app")
public class Application extends SpringBootServletInitializer {

	@Override
	protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		return application.sources(Application.class).registerShutdownHook(true);
	}

	public static void main(String... args) {
		SpringApplication.run(Application.class, args);
	}
}

I created spring components as Pages then injected into Fluent..

**Comment by Toilal** [comment]
Autowiring a `FluentPage` will not work, because `FluentPage` requires `FluentControl` constructor parameter. Also, Spring injection will not occur in FluentPage too, so `browserService` will be null in your case.

So we are planning a `fluentlenium-spring` module to support the following features

- Accept @Autowired instead of @Page for Page injection (=> not sure it's doable as the FluentLenium Injection may not be consistent with the Spring Injection. But in itself, it's not a big issue, and following points are more critical).
- Allow @Autowired of fields in FluentPage.
- Allow to configure FluentLenium configuration properties from Spring context, with a Spring bean implementing `org.fluentlenium.configuration.ConfigurationProperties`.
- For configuration properties currently accepting a JavaBean Class Name  (ie. webDriver, capabilities, ...), allow to give a Spring Bean name instead available in the spring context.

**Comment by Toilal** [comment]
As a workaround for the FluentPage issue you can still use @Page, and use JUnit @Before to inject manually the context into the pages.

see http://stackoverflow.com/questions/3813588/how-to-inject-dependencies-into-a-self-instantiated-object-in-spring

**Comment by Toilal** [comment]
@jltnf54 Please read answer I posted on #337
