### ISSUE TITLE
Add modules description on the beginning on readme

### ISSUE THREAD

**Issue by filipcynarski** [FluentLenium/FluentLenium#522]
Add modules description on the beginning on readme to avoid people confusion which module is responsible for what.

**Comment by picimako** [comment]
@slawekradzyminski
How detailed description is needed? Would a one or two sentence summary be enough or longer ones are expected?
Also which document should this be added to?

**Comment by slawekradzyminski** [comment]
Hi @picimako 

It's up to you really, I don't want to micromanage open source project that belongs to community :)

I feel like to best idea is short description in main README.md and link to more detailed section in docs (which doesn't exist currently).

**Comment by tamasbalog** [comment]
@slawekradzyminski 

The reason I asked it because I am still not that experienced with FluentLenium and how things are handled, and I don't want to go against any processes that are already established and working. :)

However your suggestion seems fine. First I will go with a short summary about the modules in the main README, than later on the module specific documentation can be created.

**Comment by slawekradzyminski** [comment]
Short summary is done by @picimako

Would be nice to have also detailed description on fluentlenium.com
