### ISSUE TITLE
await().until(FluentList).displayed() does not work

### ISSUE THREAD

**Issue by gkiszczak** [FluentLenium/FluentLenium#541]
Probably it wont work for other conditions. 
 ```
...
@FindBy(css = "[data-test='custom']")
private FluentList<CustomFluentWebElement> elements;

public void customMethod() {
        await().until($("[data-test='custom']")).displayed(); 
        await().until(elements).displayed(); 
        ...
}```

both ways does not work.

**Comment by filipcynarski** [comment]
@gkiszczak I did a few PoCs and was considering few options of dealing w/ the issue reported by you.

Finally I've decided to add integration tests and update documentation because I cannot be sure that everyone wants to wait for the first item of the list to be present. In terms of dynamic pages there is no one definition what mean the list was displayed or present.

I'm living it to test developers and let you to use `Supplier` to make your tests working so instead of example which you provided you need:

 ```java
...
@FindBy(css = "[data-test='custom']")
private FluentList<CustomFluentWebElement> elements;

public void customMethod() {
       await().until(() -> $("[data-test='custom']").first().displayed()); 
       await().until(() -> elements.first().displayed()); 
       ...
}
```

If you are checking `first` element to be present you can use `get(index)` if you are waiting for another one.
