### ISSUE TITLE
Awaits with negation not() does not work as expected

### ISSUE THREAD

**Issue by TomaszSzyborski** [FluentLenium/FluentLenium#595]
In abstract base test there are waits configured
`@Wait(timeout = 10, timeUnit = TimeUnit.SECONDS, pollingInterval = 1, pollingTimeUnit = TimeUnit.SECONDS)
@FluentConfiguration(webDriver="chrome")
public abstract class BaseTest extends FluentTestNg{`

but the test fail without waiting for page to load entirely, or for element's presence (clickable etc. etc.)

in other tests wait is in more explicit manner:
`
FluentWebElement elem = el(<selector>);
        await()
                .atMost(10,
                        TimeUnit.SECONDS)
                .pollingEvery(250, TimeUnit.MILLISECONDS)
                .until(elem)
        .not()
                .present();
`
Fluent waits for entire 10 seconds before proceding. Even though given element is not present after 4 seconds.

**Comment by filipcynarski** [comment]
It may be related w/ #593

**Comment by koryl** [comment]
It can be related to #491, which is on develop branch.
I think second issue is strictly related to usage not() and it needs further investigation.

**Comment by slawekradzyminski** [comment]
I was debugging it for quite a while today and I suspect the code below does not work because we throw NoSuchElementException.

```java
await().until(el).not.displayed()
```
 Please take a look how FluentLenium currently works here:

https://github.com/FluentLenium/FluentLenium/blob/develop/fluentlenium-assertj/src/test/java/org/fluentlenium/assertj/integration/element/FluentWebElementDisplayedTest.java

I assume that if we handle NoSuchElementException in enabled(), selected(), displayed() and clickable() methods our awaits may start working better.

**Comment by slawekradzyminski** [comment]
Done
