### ISSUE TITLE
FluentLenium 3.8 Release with Java 8

### ISSUE THREAD

**Issue by koryl** [FluentLenium/FluentLenium#702]
Update FluentLenium 3.X branch to newest libraries.
Note: FluentLenium 3.X is compatible with JDK 1.8+ and FluentLenium 4.X is compatible with JDK 11+.

**Comment by christian-draeger** [comment]
Just a question, is version 4x actively using java 11 features?
Otherwise it should be preferred to keep it compatible with the lowest java version as possible (e.g. jdk8).
The majority  of my current projects are written in kotlin (which has support down to jdk 8 in it's latest version). using fluentlenium 4x forced me to upgrade to jdk11, not a big issue at this time but it can be a real deal in bigger legacy projects.

**Comment by slawekradzyminski** [comment]
New features has been backported to Java 8.

https://github.com/FluentLenium/FluentLenium/releases
